# Form implementation generated from reading ui file '.\VentanaAgregarSubTarea.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmAgregarSubTarea(object):
    def setupUi(self, frmAgregarSubTarea):
        frmAgregarSubTarea.setObjectName("frmAgregarSubTarea")
        frmAgregarSubTarea.resize(750, 576)
        frmAgregarSubTarea.setMinimumSize(QtCore.QSize(750, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/icono_principal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmAgregarSubTarea.setWindowIcon(icon)
        self.formLayoutWidget = QtWidgets.QWidget(parent=frmAgregarSubTarea)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 70, 691, 411))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblTitulo = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblTitulo.setObjectName("lblTitulo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitulo)
        self.txtTitulo = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtTitulo.setObjectName("txtTitulo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTitulo)
        self.lblDescripcion = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblDescripcion.setObjectName("lblDescripcion")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblDescripcion)
        self.rtxtDescripcion = QtWidgets.QTextEdit(parent=self.formLayoutWidget)
        self.rtxtDescripcion.setObjectName("rtxtDescripcion")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rtxtDescripcion)
        self.lblFechaLimite = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblFechaLimite.setObjectName("lblFechaLimite")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFechaLimite)
        self.dtpFechaLimite = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.dtpFechaLimite.setCalendarPopup(True)
        self.dtpFechaLimite.setObjectName("dtpFechaLimite")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dtpFechaLimite)
        self.lblAgregarsubTarea = QtWidgets.QLabel(parent=frmAgregarSubTarea)
        self.lblAgregarsubTarea.setGeometry(QtCore.QRect(30, 20, 691, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblAgregarsubTarea.setFont(font)
        self.lblAgregarsubTarea.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.lblAgregarsubTarea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAgregarsubTarea.setObjectName("lblAgregarsubTarea")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=frmAgregarSubTarea)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 500, 691, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAgregarSubTarea = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/aceptar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAgregarSubTarea.setIcon(icon1)
        self.btnAgregarSubTarea.setIconSize(QtCore.QSize(24, 24))
        self.btnAgregarSubTarea.setObjectName("btnAgregarSubTarea")
        self.horizontalLayout.addWidget(self.btnAgregarSubTarea)
        self.btnCancelar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/cancelar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCancelar.setIcon(icon2)
        self.btnCancelar.setIconSize(QtCore.QSize(24, 24))
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(frmAgregarSubTarea)
        QtCore.QMetaObject.connectSlotsByName(frmAgregarSubTarea)

    def retranslateUi(self, frmAgregarSubTarea):
        _translate = QtCore.QCoreApplication.translate
        frmAgregarSubTarea.setWindowTitle(_translate("frmAgregarSubTarea", "::Sistema Gestión de Tareas:: Agregar Sub Tarea"))
        self.lblTitulo.setText(_translate("frmAgregarSubTarea", "Titulo:"))
        self.lblDescripcion.setText(_translate("frmAgregarSubTarea", "Descripción: "))
        self.lblFechaLimite.setText(_translate("frmAgregarSubTarea", "Fecha Límite:"))
        self.lblAgregarsubTarea.setText(_translate("frmAgregarSubTarea", "Agregar Sub-Tarea"))
        self.btnAgregarSubTarea.setText(_translate("frmAgregarSubTarea", "Agregar Sub Tarea"))
        self.btnAgregarSubTarea.setShortcut(_translate("frmAgregarSubTarea", "Ctrl+Return"))
        self.btnCancelar.setText(_translate("frmAgregarSubTarea", "Cancelar"))
        self.btnCancelar.setShortcut(_translate("frmAgregarSubTarea", "Esc"))
