# Form implementation generated from reading ui file '.\VentanaAcercaDe.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmAcercaDe(object):
    def setupUi(self, frmAcercaDe):
        frmAcercaDe.setObjectName("frmAcercaDe")
        frmAcercaDe.resize(750, 487)
        frmAcercaDe.setMinimumSize(QtCore.QSize(750, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/icono_principal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmAcercaDe.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=frmAcercaDe)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 691, 362))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(".\\../src/recursos/imagenes/logoUcuenca.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblUniversidad = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lblUniversidad.setObjectName("lblUniversidad")
        self.verticalLayout.addWidget(self.lblUniversidad)
        self.lblVersionPrograma = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lblVersionPrograma.setObjectName("lblVersionPrograma")
        self.verticalLayout.addWidget(self.lblVersionPrograma)
        self.lblRealizadoPor = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lblRealizadoPor.setObjectName("lblRealizadoPor")
        self.verticalLayout.addWidget(self.lblRealizadoPor)
        self.lblFacultad = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lblFacultad.setObjectName("lblFacultad")
        self.verticalLayout.addWidget(self.lblFacultad)
        self.lblCarrera = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lblCarrera.setObjectName("lblCarrera")
        self.verticalLayout.addWidget(self.lblCarrera)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.btnRegresar = QtWidgets.QPushButton(parent=frmAcercaDe)
        self.btnRegresar.setGeometry(QtCore.QRect(290, 440, 181, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/regresar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnRegresar.setIcon(icon1)
        self.btnRegresar.setIconSize(QtCore.QSize(24, 24))
        self.btnRegresar.setObjectName("btnRegresar")
        self.lblTitulo = QtWidgets.QLabel(parent=frmAcercaDe)
        self.lblTitulo.setGeometry(QtCore.QRect(30, 30, 691, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")

        self.retranslateUi(frmAcercaDe)
        QtCore.QMetaObject.connectSlotsByName(frmAcercaDe)

    def retranslateUi(self, frmAcercaDe):
        _translate = QtCore.QCoreApplication.translate
        frmAcercaDe.setWindowTitle(_translate("frmAcercaDe", "::Sistema Gestión de Tareas:: Acerca de"))
        self.lblUniversidad.setText(_translate("frmAcercaDe", "Universidad de Cuenca"))
        self.lblVersionPrograma.setText(_translate("frmAcercaDe", "Versión del programa: Alpha"))
        self.lblRealizadoPor.setText(_translate("frmAcercaDe", "Realizado por: Daniel Mateo Salcedo Seminario"))
        self.lblFacultad.setText(_translate("frmAcercaDe", "Facultad de Ingeniería"))
        self.lblCarrera.setText(_translate("frmAcercaDe", "Carrera de Computación"))
        self.btnRegresar.setText(_translate("frmAcercaDe", "Regresar"))
        self.btnRegresar.setShortcut(_translate("frmAcercaDe", "Esc"))
        self.lblTitulo.setText(_translate("frmAcercaDe", "Acerca de"))
