# Form implementation generated from reading ui file '.\VentanaCalendario.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmCalendario(object):
    def setupUi(self, frmCalendario):
        frmCalendario.setObjectName("frmCalendario")
        frmCalendario.resize(750, 600)
        frmCalendario.setMinimumSize(QtCore.QSize(750, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/icono_principal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmCalendario.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=frmCalendario)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 711, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblListadoAsignaturas = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.lblListadoAsignaturas.setFont(font)
        self.lblListadoAsignaturas.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblListadoAsignaturas.setObjectName("lblListadoAsignaturas")
        self.verticalLayout.addWidget(self.lblListadoAsignaturas)
        self.dtpCalendario = QtWidgets.QCalendarWidget(parent=self.verticalLayoutWidget)
        self.dtpCalendario.setObjectName("dtpCalendario")
        self.verticalLayout.addWidget(self.dtpCalendario)
        self.layoutWidget = QtWidgets.QWidget(parent=frmCalendario)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 520, 711, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnVerEventos = QtWidgets.QPushButton(parent=self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/ver_actividades.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnVerEventos.setIcon(icon1)
        self.btnVerEventos.setIconSize(QtCore.QSize(24, 24))
        self.btnVerEventos.setObjectName("btnVerEventos")
        self.horizontalLayout.addWidget(self.btnVerEventos)
        self.btnRegresar = QtWidgets.QPushButton(parent=self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/regresar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnRegresar.setIcon(icon2)
        self.btnRegresar.setIconSize(QtCore.QSize(24, 24))
        self.btnRegresar.setObjectName("btnRegresar")
        self.horizontalLayout.addWidget(self.btnRegresar)

        self.retranslateUi(frmCalendario)
        QtCore.QMetaObject.connectSlotsByName(frmCalendario)

    def retranslateUi(self, frmCalendario):
        _translate = QtCore.QCoreApplication.translate
        frmCalendario.setWindowTitle(_translate("frmCalendario", "::Sistema Gestión de Tareas:: Calendario"))
        self.lblListadoAsignaturas.setText(_translate("frmCalendario", "Calendario de actividades"))
        self.btnVerEventos.setText(_translate("frmCalendario", "Ver Tareas"))
        self.btnVerEventos.setShortcut(_translate("frmCalendario", "Return"))
        self.btnRegresar.setText(_translate("frmCalendario", "Regresar"))
        self.btnRegresar.setShortcut(_translate("frmCalendario", "Esc"))
