# Form implementation generated from reading ui file '.\VentanaAgregarAsignatura.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmAgregarAsignatura(object):
    def setupUi(self, frmAgregarAsignatura):
        frmAgregarAsignatura.setObjectName("frmAgregarAsignatura")
        frmAgregarAsignatura.resize(750, 400)
        frmAgregarAsignatura.setMinimumSize(QtCore.QSize(410, 276))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/icono_principal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmAgregarAsignatura.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=frmAgregarAsignatura)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 320, 671, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAgregar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/agregar_asignatura.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAgregar.setIcon(icon1)
        self.btnAgregar.setIconSize(QtCore.QSize(24, 24))
        self.btnAgregar.setObjectName("btnAgregar")
        self.horizontalLayout.addWidget(self.btnAgregar)
        self.btnCancelar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../src/recursos/iconos/cancelar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCancelar.setIcon(icon2)
        self.btnCancelar.setIconSize(QtCore.QSize(24, 24))
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.lblAgregarAsignatura = QtWidgets.QLabel(parent=frmAgregarAsignatura)
        self.lblAgregarAsignatura.setGeometry(QtCore.QRect(20, 20, 691, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblAgregarAsignatura.setFont(font)
        self.lblAgregarAsignatura.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.lblAgregarAsignatura.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAgregarAsignatura.setObjectName("lblAgregarAsignatura")
        self.formLayoutWidget = QtWidgets.QWidget(parent=frmAgregarAsignatura)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 100, 671, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblNombre = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblNombre.setObjectName("lblNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblNombre)
        self.txtNombre = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNombre)
        self.lblCodigoAsignatura = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblCodigoAsignatura.setObjectName("lblCodigoAsignatura")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblCodigoAsignatura)
        self.txtCodigoAsignatura = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtCodigoAsignatura.setObjectName("txtCodigoAsignatura")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtCodigoAsignatura)
        self.lblDocente = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblDocente.setObjectName("lblDocente")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblDocente)
        self.cbxDocente = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.cbxDocente.setObjectName("cbxDocente")
        self.cbxDocente.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbxDocente)

        self.retranslateUi(frmAgregarAsignatura)
        QtCore.QMetaObject.connectSlotsByName(frmAgregarAsignatura)

    def retranslateUi(self, frmAgregarAsignatura):
        _translate = QtCore.QCoreApplication.translate
        frmAgregarAsignatura.setWindowTitle(_translate("frmAgregarAsignatura", "::Sistema Gestión de Tareas:: Agregar Asignatura"))
        self.btnAgregar.setText(_translate("frmAgregarAsignatura", "Agregar"))
        self.btnAgregar.setShortcut(_translate("frmAgregarAsignatura", "Return"))
        self.btnCancelar.setText(_translate("frmAgregarAsignatura", "Cancelar"))
        self.btnCancelar.setShortcut(_translate("frmAgregarAsignatura", "Esc"))
        self.lblAgregarAsignatura.setText(_translate("frmAgregarAsignatura", "Agregar Asignatura"))
        self.lblNombre.setText(_translate("frmAgregarAsignatura", "Nombre:"))
        self.lblCodigoAsignatura.setText(_translate("frmAgregarAsignatura", "Código Asignatura:"))
        self.lblDocente.setText(_translate("frmAgregarAsignatura", "Docente: "))
        self.cbxDocente.setItemText(0, _translate("frmAgregarAsignatura", "Ninguno"))
